// packages/mitosis/jamtools-components/library/packages/svelte/src/macro-components/components/saved_macro_values.svelte
<script context="module" lang="ts">
  export type SavedMacroValues = {
    saved: MidiEventFull[];
    onClickDelete: (event: MidiEventFull) => void;
  };
</script>

<script lang="ts">
  import type { MidiEventFull } from "@jamtools/core/modules/macro_module/macro_module_types";
  const getKeyForMidiEvent = (event: MidiEventFull) => {
    return `${event.deviceInfo.name}|${event.event.channel}|${event.event.number}`;
  };

  export let saved: SavedMacroValues["saved"];
  export let onClickDelete: SavedMacroValues["onClickDelete"];
</script>

<ul>
  {#each saved as event (getKeyForMidiEvent(event))}
    <li>
      {getKeyForMidiEvent(event)}<button
        on:click={(event) => {
          onClickDelete(event);
        }}
      >
        Delete
      </button>
    </li>
  {/each}
</ul>

// packages/jamtools/core/modules/macro_module/macro_handlers/inputs/components/saved_macro_values.tsx
import React from 'react';

import {MidiEventFull} from 'jamtools-core/modules/macro_module/macro_module_types';
import {getKeyForMidiEvent} from '../input_macro_handler_utils';
import {Button} from 'jamtools-core/components/Button';

export type SavedMacroValues = {
    saved: MidiEventFull[];
    onClickDelete: (event: MidiEventFull) => void;
};
export const SavedMacroValues = ({saved, onClickDelete}: SavedMacroValues) => {
    return (
        <ul>
            {saved.map((event) => {
                const key = getKeyForMidiEvent(event);
                return (
                    <li key={key}>
                        {key}
                        <Button
                            onClick={() => onClickDelete(event)}
                        >
                            Delete
                        </Button>
                    </li>
                );
            })}
        </ul>
    );
};
