// packages/mitosis/jamtools-components/library/packages/react/src/macro-components/components/saved_macro_values.tsx
"use client";
import * as React from "react";

export type SavedMacroValues = {
  saved: MidiEventFull[];
  onClickDelete: (event: MidiEventFull) => void;
};
import type { MidiEventFull } from "@jamtools/core/modules/macro_module/macro_module_types";
const getKeyForMidiEvent = (event: MidiEventFull) => {
  return `${event.deviceInfo.name}|${event.event.channel}|${event.event.number}`;
};

function SavedMacroValues(props: SavedMacroValues) {
  return (
    <ul>
      {props.saved?.map((event) => (
        <li key={getKeyForMidiEvent(event)}>
          {getKeyForMidiEvent(event)}
          <button onClick={(event) => props.onClickDelete(event)}>
            Delete
          </button>
        </li>
      ))}
    </ul>
  );
}

export default SavedMacroValues;

// packages/mitosis/jamtools-components/library/packages/svelte/src/macro-components/components/saved_macro_values.svelte
<script context="module" lang="ts">
  export type SavedMacroValues = {
    saved: MidiEventFull[];
    onClickDelete: (event: MidiEventFull) => void;
  };
</script>

<script lang="ts">
  import type { MidiEventFull } from "@jamtools/core/modules/macro_module/macro_module_types";
  const getKeyForMidiEvent = (event: MidiEventFull) => {
    return `${event.deviceInfo.name}|${event.event.channel}|${event.event.number}`;
  };

  export let saved: SavedMacroValues["saved"];
  export let onClickDelete: SavedMacroValues["onClickDelete"];
</script>

<ul>
  {#each saved as event (getKeyForMidiEvent(event))}
    <li>
      {getKeyForMidiEvent(event)}<button
        on:click={(event) => {
          onClickDelete(event);
        }}
      >
        Delete
      </button>
    </li>
  {/each}
</ul>
