// packages/jamtools/core/modules/macro_module/macro_handlers/inputs/components/react/src/components/saved_macro_values.tsx
"use client";
import * as React from "react";

export type SavedMacroValues = {
  saved: MidiEventFull[];
  onClickDelete: (event: MidiEventFull) => void;
};
import type { MidiEventFull } from "@jamtools/core/modules/macro_module/macro_module_types";
const getKeyForMidiEvent = (event: MidiEventFull) => {
  return `${event.deviceInfo.name}|${event.event.channel}|${event.event.number}`;
};

function SavedMacroValues(props: SavedMacroValues) {
  return (
    <ul>
      {props.saved?.map((midiEvent) => (
        <li key={getKeyForMidiEvent(midiEvent)}>
          {getKeyForMidiEvent(midiEvent)}
          <button onClick={(event) => props.onClickDelete(midiEvent)}>
            Delete
          </button>
        </li>
      ))}
    </ul>
  );
}

export default SavedMacroValues;

// packages/jamtools/core/modules/macro_module/macro_handlers/inputs/components/svelte/src/components/saved_macro_values.svelte
<script context="module" lang="ts">
  export type SavedMacroValues = {
    saved: MidiEventFull[];
    onClickDelete: (event: MidiEventFull) => void;
  };
</script>

<script lang="ts">
  import type { MidiEventFull } from "@jamtools/core/modules/macro_module/macro_module_types";
  const getKeyForMidiEvent = (event: MidiEventFull) => {
    return `${event.deviceInfo.name}|${event.event.channel}|${event.event.number}`;
  };

  export let saved: SavedMacroValues["saved"];
  export let onClickDelete: SavedMacroValues["onClickDelete"];
</script>

<ul>
  {#each saved as midiEvent (getKeyForMidiEvent(midiEvent))}
    <li>
      {getKeyForMidiEvent(midiEvent)}<button
        on:click={(event) => {
          onClickDelete(midiEvent);
        }}
      >
        Delete
      </button>
    </li>
  {/each}
</ul>
